### ISSUE TITLE
Triton version?

### ISSUE THREAD

**Issue by YicongHong** [Hprairie/Bi-Mamba2#2]
Hi Hayden, Thanks for your amazing development of bimamba2! I tried to follow the [Module API ](https://github.com/Hprairie/Bi-Mamba2?tab=readme-ov-file#module-api) but got some errors with Triton-2.1.0 (I used this for Mamba and Mamba-2 and Hydra), just want to confirm what is the correct version to use?

With Triton-2.1.0, I got "AttributeError: module 'triton.language' has no attribute 'flip'".

Thanks!

**Comment by Liu-zhi-chao** [comment]
> Hi Hayden, Thanks for your amazing development of bimamba2! I tried to follow the [Module API ](https://github.com/Hprairie/Bi-Mamba2?tab=readme-ov-file#module-api) but got some errors with Triton-2.1.0 (I used this for Mamba and Mamba-2 and Hydra) and Triton-3.0.0, just want to confirm what is the correct version to use?
> 
> With Triton-2.1.0, I got "AttributeError: module 'triton.language' has no attribute 'flip'".
> 
> Thanks!

I have also faced the same problem as yours. You can install Triton-3.0.0 to solve this problem.

**Comment by Hprairie** [comment]
Yes I should add a note about that. I have only used triton 3.0.0
